#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Candide Welfare Foundation
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  Helping Communities for combined progress.
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Founded in 2019, CWF have been at forefront for social harmony, eduction initiatives, professional trainings and emergency aid in Pakistan.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: info@candide.org.pk
org_street_address: Farid Tower #Please include suite number on the line below
org_address_suite: Office 208
org_city: Lahore
org_state: Punjab
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  54700
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  03328517590

#SOCIAL MEDIA
org_twitter_username: cwf_pakistan
org_facebook_username: candide-welfare
org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: 
tinyletter_username: candidetech

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: two

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
